src/app/AppLayout.tsx
src/components/navigation/navigation.stories.tsx
src/components/navigation/navigation.tsx
src/pages/home/homePage.tsx
src/stores/navigationStore.ts

- #24 
- 네이게이션바 제작
- 현재 선택한 네비게이션 스토어 생성
- 네비게이션 컴포넌트 개발
- 없음

[Feat] Navigation 추가

---

package.json
pnpm-lock.yaml
src/App.tsx
src/api/axios.ts
src/api/services/user/group/quries.ts
src/api/services/user/group/service.ts
src/app/AppLayout.tsx
src/components/dropdown/groupDropDown.tsx
src/components/header/header.tsx
src/components/navigation/navigation.tsx
src/components/ui/dropdown-menu.tsx
src/mocks/handlers/groupHandlers.ts
src/mocks/handlers/index.ts
src/pages/home/homePage.tsx
src/stores/groupStore.ts
src/styles/globals.css
src/styles/layout.css

- #29 
- drodown 공통 컴포넌트 개발
- group dropdown 컴포넌트 개발
- api 연결 테스트
- 공통 컴포넌트 개발
- 디자인 수정
- msw 테스트 케이스 추가
- tanstack query 설정 추가
- 없음

[Feat] DropDown 공통 컴포넌트 개발

---

src/api/services/user/model.ts
src/api/services/user/quries.ts
src/api/services/user/service.ts
src/api/services/vote/model.ts
src/api/services/vote/quries.ts
src/api/services/vote/service.ts
src/components/navigation/navigation.tsx
src/components/ui/button.tsx
src/components/ui/form.tsx
src/components/ui/input.tsx
src/components/ui/textarea.tsx
src/features/home/components/swipCard.tsx
src/features/home/pages/homePage.tsx
src/features/make/components/makeVoteForm.tsx
src/features/make/lib/makeVoteSchema.ts
src/lib/globalTime2LocalTime.ts
src/mocks/handlers/voteCardHandlers.ts
src/stores/userStore.ts

- #42
- input 공통 컴포넌트 제작
- form 공통 컴포넌트 제작
- 투표 등록 폼 제작
- 투표 등록 api 테스트
- 투표 등록 폼 개발
- 공통 input, textarea, form 컴포넌트 제작
- msw 테스트 추가
- `useCreateVoteMutation` 추가
- 없음

[Feat] input 공통 컴포넌트 제작

---

src/app/router.tsx
src/components/card/voteCardPreview.tsx
src/features/make/components/voteCardPreviewModal.tsx
src/features/make/pages/makePage.tsx

- #31 
- 투표 등록 모달 개발
- 투표 등록 페이지 개발
- form, input, textarea 공통 컴포넌트 개발
- 투표 등록 커스텀 모달 개발
- 투표 등록 커스텀 카드 제작
- 투표 등록 페이지 개발
- 투표 등록 테스트 msw 설정
- 투표 등록 `useCreateVoteMutate` 추가
- 없음

[Feat] 투표등록 페이지 개발

---

src/app/AppLayout.tsx
src/app/router.tsx
src/components/navigation/navigation.tsx
src/features/login/pages/authCallback.tsx
src/features/login/pages/loginPage.tsx
src/stores/navigationStore.ts

- #44
- 네비게이션 동작 이상 해결
- 동적 라우팅 추가
- tab과 url이 어긋나던 오류 해결
- 동적 라우팅 추가
- 없음

[Feat] navgtaion 오류 해결

---

src/api/services/vote/model.ts
src/api/services/vote/quries.ts
src/api/services/vote/service.ts
src/app/router.tsx
src/components/item/voteItem.tsx
src/components/list/voteList.tsx
src/features/research/components/researchList.tsx
src/features/research/components/topList.tsx
src/features/research/pages/researchPage.tsx
src/mocks/handlers/voteCardHandlers.ts
src/styles/utilities/shadow.css

- #32 
- 투표 결과 페이지 개발
- 투표 결과 리스트 컴포넌트 개발
- 투표 결과 리스트 아이템 컴포넌트개발
- `useParticipatedVotesInfinityQuery` 참여한 투표 조회 쿼리 추가
- `useCreateVotesInfinityQuery` 생성한 투표 조회 쿼리 추가
- 없음

[Feat] 투표 결과 페이지 개발

---

package.json
pnpm-lock.yaml
src/api/services/vote/model.ts
src/components/card/voteCardPreview.tsx
src/components/ui/checkbox.tsx
src/features/make/components/makeVoteForm.tsx
src/features/make/components/voteCardPreviewModal.tsx
src/features/make/lib/makeVoteSchema.ts

- #53 
- 투표 등록 페이지 `익명` 관련 로직 추가
- 익명 관련 폼 추가
- 익명 입력 요소 추가
- mutate의 쿼리에 익명 요소 추가
- 없음

[BuxFix] 투표등록페이지 API오류 해결

---

src/api/services/vote/model.ts
src/api/services/vote/quries.ts
src/api/services/vote/service.ts
src/app/router.tsx
src/components/item/voteItem.tsx
src/features/research/pages/researchDetail.Page.tsx
src/mocks/handlers/index.ts
src/mocks/handlers/researchHandlers.ts
src/styles/utilities/color.css

- #33 
- 투표 상세 페이지 개발
- 투표결과 페이지 item 기능 수정
- 투표 상세 페이지 디자인 개발
- 투표 상세 페이지 msw 코드 작성
- 투표 상세 페이지 query 작성
- `useVoteDetailInfo` , `useVoteDetailResults` 작성
- 투표 결과 페이지 item이 상태 `PENDING, REJECT` 상태 시 이동 불가능 & 마우스 디자인 변경
- 없음

[Feat] 투표상세 페이지 개발

---

src/components/card/voteCard.tsx
src/components/card/voteEndCard.tsx
src/components/navigation/navigation.tsx
src/features/home/components/swipCard.tsx
src/features/home/components/voteSwiper_framer.tsx
src/features/home/pages/homePage.tsx
src/features/home/stores/voteCardStore.ts

- #58
- 디자인 변경
- 배포 오류 수정
- 무한스크롤 호출 오류 해결
- 페이지 이동시 자동 요청 로직 추가
- 배포 모달 오픈 시점의 무한로딩 오류 해결
- 블링크 최소화 진행 -> 실패
- 없음

[Feat] 홈의 무한 스크롤 및 블링크 오류 수정

---

src/app/AppLayout.tsx
src/components/card/voteCard.tsx
src/components/card/voteCardPreview.tsx
src/components/card/voteNoMoreCard.tsx
src/components/item/voteItem.tsx
src/components/modal/loginRequiredModal.tsx
src/components/modal/modal.tsx
src/components/modal/noVoteAvailableModal.tsx
src/components/navigation/navigation.tsx
src/features/group/components/createGroupForm.tsx
src/features/home/components/voteSwiper_framer.tsx
src/features/home/pages/homePage.tsx
src/features/login/pages/authCallback.tsx
src/features/make/components/makeVoteForm.tsx
src/features/make/components/voteCardPreviewModal.tsx
src/features/research/pages/researchDetail.Page.tsx
src/features/user/pages/userPage.tsx
src/mocks/handlers/userHandlers.ts

- #60
- 모달 스타일 수정
- 토스트메세지 추가
- 투표 줄변경 추가
- 재로그인 로직 추가
- modal 취소 오류 해결
- 모달 너비 스타일 조정
- 토스트메세지 전역로직 추가
- 투표 및 미리보기 줄변경 추가
- 모달 최상위 한번만 렌더링 및 취소 오류 해결
- 로그인 정보가 없다면 자동으로 쿠키로 재 로그인 진행 추가
- 없음

[bugfix] 배포 QA 1차 수정

---

package.json
src/api/services/user/group/quries.ts
src/api/services/vote/model.ts
src/api/services/vote/quries.ts
src/api/services/vote/service.ts
src/app/AppLayout.tsx
src/app/QueryProvider.tsx
src/components/dropdown/groupDropDown.tsx
src/components/item/voteItem.tsx
src/components/modal/addGroupModal.tsx
src/components/modal/exitUserModal.tsx
src/components/modal/loginRequiredModal.tsx
src/features/home/components/swipCard.tsx
src/features/home/components/tutorial.tsx
src/features/home/pages/homePage.tsx
src/features/login/pages/authCallback.tsx
src/features/make/components/makeVoteForm.tsx
src/features/user/components/userCard.tsx
src/features/user/lib/userSchema.ts
src/lib/fullReset.ts
src/lib/messageMap.ts
src/stores/groupStore.ts
src/stores/tutorialStore.ts
src/stores/userStore.ts
src/styles/globals.css

- 스타일 개선
- 새로고침 강제 home 이동 수정
- mutate 후 캐시 최신화 추가
- 로직 에러 수정
- 폰트 파일명 오류 수정
- 취소 버튼 강제 이동 제거
- 홈 2중 호출 에러 수정
- 전역함수 초기화 로직 추가
- 전체 그룹 추가
- 튜툐리얼 페이지 제작 및 연결
- 새로고침 페이지 이동 제거
- mutate 후 자동 캐시 최신화 적용
- 없음

[Feat] QA 2차 수정

---

src/api/services/user/quries.ts
src/api/services/vote/quries.ts
src/app/AppLayout.tsx
src/components/card/groupCard.tsx
src/components/card/voteCard.tsx
src/components/card/voteCardPreview.tsx
src/components/header/header.tsx
src/components/item/voteItem.tsx
src/features/group/components/createGroupForm.tsx
src/features/home/components/tutorial.tsx
src/features/home/components/voteSwiper_framer.tsx
src/features/home/pages/homePage.tsx
src/features/research/components/researchList.tsx
src/features/user/components/userCard.tsx
src/stores/userStore.ts

- mutate 호출 시 캐시 최신화
- 그룹 이름 띄어쓰기 허용
- 투표마다 요청 발생하도록 개선
- 생성 투표 상태에 따른 디자인 변경
- refresh후 nickname도 반영
- 텍스트 오류 수정
- form 입력 조건 수정
- 투표 batch 제거
- 투표 생성 상태에 따라, 진행 막대바, 종료 시간 삭제
- 카드 강제 줄변경 적용
- 튜토리얼 open시 모달 열리지 않음
- 그룹 카드에 초대코드 복사 추가
- 없음

[Feat] QA3

---

src/features/research/pages/researchDetail.Page.tsx
src/lib/toKSTISOString.ts

[PRD] 시간 수정 배포

---

src/features/home/components/tutorial.tsx

style: 튜툐리얼 스타일 조정

---

src/components/card/voteCard.tsx
src/components/card/voteCardPreview.tsx
src/features/home/components/tutorial.tsx

- #71 
- 튜툐리얼 페이지 절대위치 요소 위치 조정
- 투표 카드 폰트 조정
- 절대 위치에 transform으로 위치 세부 조정
- 투표 카드의 제목은 공용 폰트인 `pyeojinGothic` 으로 변경
- 없음

[Style] 튜토리얼 스타일 수정

---

src/stores/groupStore.ts

- #72 
- 드롭다운을 초기화하는 로직 수정
- 초기화가 0번이 아닌 1번으로 시도되면서 "전체"가 아닌 "공개"로 요청이 가는 오류 해결
- 없음

[Bugfix] 드롭다운 초기화 오류 수정

---

src/features/home/components/swipCard.tsx
src/features/home/components/voteDirectionButtonGroup.tsx
src/features/home/components/voteSwiper_framer.tsx

- #78 
- 스와이프 버튼 추가
- 스와이프 라벨 제거 및 버튼 강조로 변경
- 버튼 스와이프 기능 추가
- 스와이프 라벨 제거 -> 버튼 강조로 변경
- 투표 라벨을 버튼 강조로 변경
- 라벨과 투표 버튼이 동일한 디자인으로 반복되서 UI가 어색함, 일단 제거 or 문구 변경 필요

[Feature] 스와이프버튼 추가

---

src/features/home/components/swipCard.tsx

[CICD] build 오류 해결

---

src/components/card/voteCardPreview.tsx
src/lib/formatTime.ts

[Bugfix] 투표 등록 미리보기 타이머 오류 수정

---

public/moa_app_logo.svg
src/assets/pass.svg

- #95
- 로고 배경 제거
- "기권" 버튼 색상 변경
- 기권 버튼 색상 변경
- 로고 배경 제거
- 없음

[Style] 로고, 버튼 색상 조정

---

src/components/card/groupCard.tsx
src/components/dropdown/groupDropDown.tsx
src/components/item/voteItem.tsx
src/components/modal/addGroupModal.tsx
src/components/modal/exitUserModal.tsx
src/features/group/components/createGroupForm.tsx
src/features/home/components/swipCard.tsx
src/features/login/components/kakaoButton.tsx
src/features/make/components/makeVoteForm.tsx
src/features/make/components/voteCardPreviewModal.tsx
src/features/research/components/researchList.tsx
src/features/user/components/userCard.tsx
src/features/user/components/userFeedbackWidget.tsx

- #115
- ga4 도입
- dev FE 기준 이벤트 측정 준비
- ga4 트래킹 도입
- 이벤트 트래킹 도입
- 없음

feat: GA4 도입 및 이벤트 트리거 추가

---

src/components/header/header.tsx
src/features/make/components/makeVoteForm.tsx
src/features/make/lib/makeVoteSchema.ts

- #121 
- 투표 등록 글자 수 제한 변경
- 기존 글자 255자 제한을 100자 제한으로 변경
- `header` 내 링크 이동을 div에서 a태그로 변경
- 없음

feat: 투표 등록 글자 제한 변경

---

src/app/AppLayout.tsx
src/features/group/components/createGroupForm.tsx
src/features/make/components/makeVoteForm.tsx
src/features/make/components/voteCardPreviewModal.tsx
src/features/user/components/userCard.tsx
src/features/user/lib/userSchema.ts
src/mocks/handlers/imageHandlers.ts
src/mocks/handlers/index.ts

- #160 
- #162 
- 닉네임 글자 수 제한 변경 및 폰트 크기 조절
- 이미지 presigned 저장 로직 추가
- 닉네임 글자 수 18자로 확장, 폰트 20px로 조절
- 이미지 업로드 presigned 저장 로직 추가
- 없음

feat: 이미지 업로드 기능 추가, 닉네임 글자수 수정

---

src/api/services/vote/model.ts
src/api/services/vote/queries.ts
src/api/services/vote/service.ts
src/app/router.tsx
src/components/header/header.tsx
src/components/item/voteItem.tsx
src/components/modal/modal.tsx
src/components/modal/voteCreateFailModal.tsx
src/features/make/components/makeVoteForm.tsx
src/features/make/components/voteCardPreviewModal.tsx
src/lib/messageMap.ts
src/mocks/handlers/voteCardHandlers.ts

- #168 
- 투표 검열 사유 확인 컴포넌트 추가
- 투표 삭제, 수정 쿼리 추가
- 모달 높이 스타일 오류 수정
- 투표 검열 컴포넌트 추가
- 투표 검열 사유 조회, 수정, 삭제 쿼리 추가
- `useVoteReportReasons`, `useUpdateVoteMutation`, `useDeleteVoteMutation`
- 없음

feat: 투표 검열 사유 확인, 투표 수정 삭제 추가

---

package.json
pnpm-lock.yaml
src/api/services/group/model.ts
src/api/services/group/queries.ts
src/api/services/group/service.ts
src/app/router.tsx
src/components/card/groupCard.tsx
src/components/comment/commentItem.tsx
src/components/list/memberList.tsx
src/components/modal/addGroupModal.tsx
src/components/modal/deleteGroupModal.tsx
src/components/ui/tooltip.tsx
src/features/group/components/groupMember.tsx
src/features/group/components/groupReport.tsx
src/features/group/components/updateGroupForm.tsx
src/features/group/lib/groupSchema.ts
src/features/group/pages/groupVotesPage.tsx
src/features/group/pages/manageGroupPage.tsx
src/mocks/handlers/groupHandlers.ts

- Closes #167
- 그룹 수정, 삭제, 떠나기 기능 추가
- 그룹 멤버 권한 변경, 멤버 추방 기능 추가
- 그룹 내 투표목록 조회 페이지 추가
- 그룹 수정, 삭제, 떠나기 쿼리 추가 `useUpdateGroupMutation`, `useDeleteGroupMutation`, `useLeaveGroupMutation`
- 그룹 멤버 권한 변경, 멤버 추방 쿼리 추가 `useGroupRoleChangeMutation`, `useGroupMemberDeleteMutation`
- 그룹 내 투표목록 조회 무한스크롤 쿼리 추가 `useGroupVotesInfiniteQuery` 
- 그룹 관리 페이지, 그룹 내 투표 목록 페이지 추가
- 유저페이지 그룹 떠나기, 관리 아이콘 추가
- 없음

feat: 그룹 관련 기능 개발

---

src/api/services/group/queries.ts
src/api/services/notification/model.ts
src/api/services/notification/queries.ts
src/api/services/notification/service.ts
src/app/AppLayout.tsx
src/app/QueryProvider.tsx
src/components/header/header.tsx
src/components/item/notificationItem.tsx
src/components/item/voteItem.tsx
src/components/list/notificationList.tsx
src/components/modal/voteCreateFailModal.tsx
src/components/navigation/navigation.tsx
src/components/slider/slider.tsx
src/features/research/pages/researchDetail.Page.tsx
src/features/user/components/userGroupList.tsx
src/lib/messageMap.ts
src/mocks/handlers/index.ts
src/mocks/handlers/notificationHandlers.ts
src/stores/sliderStore.ts

- Closes #175 
- 알림 컴포넌트 개발
- 알림 기능 개발
- 알림 리스트, 아이템 컴포넌트 개발
- 알림이 보여질 슬라이드 컴포넌트 개발
- 알림 msw 추가
- 알림 조회 `useInfiniteNotificationQuery`, 알림 읽음 처리 ` useMutationReadNotification` 쿼리 추가
- 없음

feat: 알림 기능 추가

---

src/api/services/comment/queries.ts
src/api/services/comment/service.ts
src/api/services/group/queries.ts
src/api/services/notification/queries.ts
src/api/services/vote/queries.ts
src/components/dropdown/groupDropDown.tsx
src/components/header/header.tsx
src/components/list/commentList.tsx
src/components/list/groupList.tsx
src/components/list/voteList.tsx
src/features/make/components/makeVoteForm.tsx
src/features/research/components/commentInput.tsx
src/features/research/pages/researchDetail.Page.tsx
src/mocks/handlers/commentHandlers.ts

- Closes #178 
- 댓글 조회 폴링 -> 롱 폴링으로 변경
- 롱 폴링 호출용 쿼리 추가
- 전체 쿼리 의존성 방어 로직 추가
- `useLongPollingCommentListQuery` 롱 폴링 호출용 쿼리 추가
- 롤 폴링, 에러 발생 시 1회 재시도 후 실패 시 새고로침 안내
- 쿼리 enabled를 추가해서 로그인여부에 따른 요청으로 error 제거
- 없음

feat: 댓글 롱 폴링 기능 추가

---

src/api/services/comment/service.ts
src/components/card/voteCard.stories.tsx
src/components/card/voteCard.test.tsx
src/components/comment/commentItem.stories.tsx
src/components/comment/commentItem.test.tsx
src/components/comment/commentItem.tsx
src/components/dropdown/groupDropDown.test.tsx
src/components/header/header.stories.tsx
src/components/header/header.test.tsx
src/components/item/voteItem.test.tsx
src/features/research/components/commentInput.stories.tsx
src/features/research/components/commentInput.test.tsx
src/features/research/components/commentInput.tsx

- Closes #191 
- 댓글 item, input 테스트 코드 작성
- 롱 폴링 시간초과 30초로 설정
- 댓글 item, input 단위, 통합 테스트 코드 작성
- 롱 폴링 시간초과 기존 10초에서 30초로 변경
- 없음

feat: 댓글 도메인 테스트 코드 추가

---

src/components/comment/commentItem.tsx
src/components/dropdown/groupDropDown.tsx
src/components/header/header.tsx
src/components/item/voteItem.tsx
src/components/list/commentList.tsx
src/components/list/researchList.tsx
src/components/list/voteList.tsx
src/components/ui/input.tsx
src/features/group/components/groupReport.tsx
src/features/group/pages/manageGroupPage.tsx
src/features/make/components/makeVoteForm.tsx
src/features/make/components/updateVoteForm.tsx
src/features/research/pages/researchPage.tsx
src/features/user/components/userFeedbackWidget.tsx
src/stores/scrollStore.ts
src/styles/layout.css
src/styles/utilities/color.css

- Closes #203
- Closes #204 
- Closes #206 
- Closes #207 
- 댓글 생성과 동시 삭제 오류 해결
- 누락된 cursor 추가
- 무한 스크롤 블링크 제거
- 스크롤 유지 기능 개선
- 댓글 롱 polling으로 가져온 댓글이 1분 이전에 삭제동작은 성공하지만, 화면에서 안사리지던 부분을 필터링 로직으로 개선
- 누락된 `cursor-pointer` 추가
- 강제 moutn시 스크롤 유지와 무한스크롤 사이에서의 충돌로 발생하는 블링크 현상을 개선
- 스크롤 유지를 새로고침 시는 초기화되도록 인메모리로 변경
- 스크롤과 무한스크롤 사이의 충돌 해결
- 무한 스크롤 요청 시 불필요한 의존성으로 2중호출되던 기능 개선
- 없음

fix: 사용자 피드백 반영

---

commitlint.config.cjs
src/components/list/commentList.tsx

- 댓글 삭제 오류 해결
- 댓글 삭제 후 필터링 로직 보완
- 없음

hotfix: v3.0.1

---

src/features/make/components/makeVoteForm.tsx
src/features/make/components/updateVoteForm.tsx
src/features/make/components/voteCardPreviewModal.tsx
src/features/make/lib/makeVoteSchema.ts

- Closes #246
- 투표 수정 버튼 비활성화 버그 픽스
- 투표 등록, 수정 시 이미지 파일 길이에 따른 좌우 여백 초과 문제 해결
- 투표 수정 image누락으로 인한 비활성화 버그 픽스
- 등록, 수정 시 이미지 파일 최대길이 적용 및 초과 내용 ...으로 적용
- 투표 등록 시작 ~ 종료 시간 안내 KST로 통일
- 없음

hotfix: v3.1.1

---

.github/workflows/aws-v3-deployment.yml
.husky/pre-commit

- 클라우드 # 148
- prod 배포 환경 변경에 따른 CI/CD 파이프라인 구축
- prod 배포 환경 변경에 따른 CI/CD 파이프라인 구축
- pre-commit 브랜치 컨벤션에 `cicd/` 추가
- 없음

cicd: prod 서버 aws 환경 CI/CD 파이프라인 구축

---

src/app/AppLayout.tsx
src/components/card/groupCard.tsx
src/components/comment/commentItem.tsx
src/components/dropdown/groupDropDown.tsx
src/components/header/header.tsx
src/components/item/notificationItem.tsx
src/components/item/voteItem.tsx
src/components/modal/modal.tsx
src/components/navigation/navigation.tsx
src/features/group/components/group/updateGroupForm.tsx
src/features/home/components/swipCard.tsx
src/features/home/components/voteSwiper_framer.tsx
src/features/research/pages/researchDetail.Page.tsx
src/features/user/components/userCard.tsx

- Closes #252
- memo를 통한 리렌더링 최적화
- dropdown, header, navigation 공통 컴포넌트 요소 `React.memo` 를 활용한 리렌더링 최적화
- home, make, research, user, group별 state로 인한 불필요한 렌더링 컴포넌트 분리, memo 적용
- 모든 Item 컴포넌트 memo 적용
- 없음

feat: 렌더링 최적화
